# Generated by Django 4.0 on 2022-07-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='profile/default.jpeg', null=True, upload_to='profile')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='resume.pdf', upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='MyYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='Short Video')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=27, null=True)),
                ('body', models.CharField(max_length=96, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectcategory')),
            ],
            options={
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='MyBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('link', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='Short Video')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectcategory')),
            ],
            options={
                'ordering': ['published'],
            },
        ),
    ]
