# Generated by Django 4.0 on 2022-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_projectcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
